# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blockchain Graveyard
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A list of all massive security breaches or thefts involving blockchains.

baseurl: "/Blockchain-Graveyard" # the subpath of your site, e.g. /blog
url: "https://magoo.github.io/Blockchain-Graveyard/" # the base hostname & protocol for your site
twitter_username: magoo
github_username:  magoo

# Build settings
markdown: kramdown
